import type { RefundRequest } from "./types";

// A realistic refund queue: clear approves, clear denies, and the dangerous middle
// (high-value, possible fraud, ambiguous) that a good agent should ESCALATE, not auto-action.
export const QUEUE: RefundRequest[] = [
  {
    id: "RF-1001",
    customer: "Maria Lopez",
    orderId: "AC-88213",
    amount: 24.0,
    currency: "USD",
    category: "Home",
    reason: "Arrived broken, the mug was shattered in the box.",
    daysSincePurchase: 4,
    itemCondition: "damaged on arrival",
    customerHistory: "first purchase",
  },
  {
    id: "RF-1002",
    customer: "Tom Becker",
    orderId: "AC-88455",
    amount: 39.99,
    currency: "USD",
    category: "Apparel",
    reason: "Changed my mind, don't want it anymore.",
    daysSincePurchase: 41,
    itemCondition: "used, worn once",
    customerHistory: "2 purchases, no prior refunds",
  },
  {
    id: "RF-1003",
    customer: "Priya Nair",
    orderId: "AC-88560",
    amount: 899.0,
    currency: "USD",
    category: "Electronics",
    reason: "Laptop stopped charging after a week.",
    daysSincePurchase: 9,
    itemCondition: "opened, possibly defective",
    customerHistory: "first purchase",
  },
  {
    id: "RF-1004",
    customer: "Derek Voss",
    orderId: "AC-88611",
    amount: 58.5,
    currency: "USD",
    category: "Beauty",
    reason: "Item not as described.",
    daysSincePurchase: 6,
    itemCondition: "opened, half used",
    customerHistory: "4 refunds in the last 30 days",
  },
  {
    id: "RF-1005",
    customer: "Alina Cho",
    orderId: "AC-88702",
    amount: 15.0,
    currency: "USD",
    category: "Home",
    reason: "Defective, the cable doesn't work.",
    daysSincePurchase: 3,
    itemCondition: "opened, defective",
    customerHistory: "first purchase",
  },
  {
    id: "RF-1006",
    customer: "Jamal Reed",
    orderId: "AC-88810",
    amount: 49.0,
    currency: "USD",
    category: "Digital",
    reason: "Didn't end up using the course.",
    daysSincePurchase: 12,
    itemCondition: "digital, fully downloaded and accessed",
    customerHistory: "first purchase",
  },
  {
    id: "RF-1007",
    customer: "Sofia Marin",
    orderId: "AC-88904",
    amount: 1240.0,
    currency: "USD",
    category: "Electronics",
    reason: "TV arrived with a cracked screen.",
    daysSincePurchase: 2,
    itemCondition: "damaged on arrival",
    customerHistory: "first purchase",
  },
  {
    id: "RF-1008",
    customer: "Owen Pratt",
    orderId: "AC-89001",
    amount: 32.0,
    currency: "USD",
    category: "Apparel",
    reason: "Wrong size sent, I ordered medium not small.",
    daysSincePurchase: 7,
    itemCondition: "unopened",
    customerHistory: "first purchase",
  },
];
